# Generated by Django migration to add default categories

from django.db import migrations


def add_categories(apps, schema_editor):
    """添加默认分类数据"""
    Category = apps.get_model('blog', 'Category')

    # 一级类目数据
    top_categories = [
        {'name': '前端', 'index': 100},
        {'name': '后端', 'index': 99},
        {'name': '数据结构与算法', 'index': 98},
        {'name': '运维', 'index': 97},
        {'name': '人工智能', 'index': 96},
    ]

    created_categories = {}

    # 创建一级类目
    for cat_data in top_categories:
        category, created = Category.objects.get_or_create(
            name=cat_data['name'],
            defaults={
                'index': cat_data['index'],
                'parent_category': None,
                'slug': cat_data['name'].lower().replace(' ', '-')
            }
        )
        created_categories[cat_data['name']] = category

    # 前端下的二级类目
    frontend_subcategories = [
        {'name': 'HTML', 'index': 100},
        {'name': 'JS', 'index': 99},
        {'name': 'CSS', 'index': 98},
        {'name': 'vue', 'index': 97},
        {'name': 'NodeJS', 'index': 96},
    ]

    frontend = created_categories.get('前端')
    if frontend:
        for sub_data in frontend_subcategories:
            Category.objects.get_or_create(
                name=sub_data['name'],
                defaults={
                    'index': sub_data['index'],
                    'parent_category': frontend,
                    'slug': sub_data['name'].lower().replace(' ', '-')
                }
            )

    # 后端下的二级类目
    backend_subcategories = [
        {'name': 'Java', 'index': 100},
        {'name': 'Go', 'index': 99},
        {'name': 'PHP', 'index': 98},
    ]

    backend = created_categories.get('后端')
    if backend:
        for sub_data in backend_subcategories:
            Category.objects.get_or_create(
                name=sub_data['name'],
                defaults={
                    'index': sub_data['index'],
                    'parent_category': backend,
                    'slug': sub_data['name'].lower().replace(' ', '-')
                }
            )

        # 将"Python技术"修改为"Python"并放到"后端"类目下
        try:
            python_category = Category.objects.get(name='Python技术')
            python_category.name = 'Python'
            python_category.parent_category = backend
            python_category.save()
        except Category.DoesNotExist:
            # 如果不存在"Python技术"，则创建"Python"
            Category.objects.get_or_create(
                name='Python',
                defaults={
                    'index': 95,
                    'parent_category': backend,
                    'slug': 'python'
                }
            )


def remove_categories(apps, schema_editor):
    """删除添加的分类数据"""
    Category = apps.get_model('blog', 'Category')

    # 删除二级类目
    subcategories = ['HTML', 'JS', 'CSS', 'vue', 'NodeJS', 'Java', 'Go', 'PHP']
    Category.objects.filter(name__in=subcategories).delete()

    # 删除一级类目
    top_categories = ['前端', '后端', '数据结构与算法', '运维', '人工智能']
    Category.objects.filter(name__in=top_categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogsettings_color_scheme'),
    ]

    operations = [
        migrations.RunPython(add_categories, remove_categories),
    ]
